### PR TITLE
Include `scm` info

### PR DESCRIPTION
**Pull request by gastaldi**
This includes the `scm` tag in the project parent

### CODE REVIEW

**Comment by ppalaga** [comment]
Nothing at all against adding the SCM info. But do we really need to change the indentation?

**Comment by ppalaga** [comment]
If this is was done by a script, then I'd recommend using [POM Tuner](https://github.com/l2x6/pom-tuner#pom-tuner)'s PomTransformer in the future because keeps the existing whitespace, comments, etc.

**Comment by gastaldi** [comment]
That's a good question. 

The indentation was changed when the Maven API flushes the Model changes to disk. I used https://github.com/gastaldi/quarkiverse-patch/blob/main/AddScm.java to change the model and some PRs were created nicely: https://github.com/quarkiverse/quarkus-poi/pull/67/files

**Comment by gastaldi** [comment]
Oh didn't know about that, let me give it a shot

**Comment by gastaldi** [comment]
@ppalaga, can you show me an example of how the following snippet would look using POM Tuner? 

```java
            Model model = Maven.readModel(parent);
            Scm scm = model.getScm();
            if (scm == null) {
                String fullName = args[0];
                scm = new Scm();
                scm.setConnection("scm:git:git@github.com:%s.git".formatted(fullName));
                scm.setDeveloperConnection("scm:git:git@github.com:%s.git".formatted(fullName));
                scm.setUrl("https://github.com/%s".formatted(fullName));
                scm.setTag("HEAD");
                model.setScm(scm);
                Maven.writeModel(model);
            }
```

**Comment by ppalaga** [comment]
Something like this should work: 

```
        new PomTransformer(Paths.get(parent), StandardCharsets.UTF_8, SimpleElementWhitespace.AUTODETECT_PREFER_EMPTY)
            .transform((Document document, TransformationContext context) -> {
                final ContainerElement scm = context.getOrAddContainerElement("scm");
                scm.addOrSetChildTextElement("connection", String.format("scm:git:git@github.com:%s.git", fullName));
                scm.addOrSetChildTextElement("developerConnection",
                        String.format("scm:git:git@github.com:%s.git", fullName));
                scm.addOrSetChildTextElement("url", String.format("https://github.com/%s", fullName));
                scm.addOrSetChildTextElement("tag", "HEAD");
            });
```

**Comment by gastaldi** [comment]
@ppalaga I think I might have found a bug. I have the following script:

```java
            new PomTransformer(parent, StandardCharsets.UTF_8, PomTransformer.SimpleElementWhitespace.AUTODETECT_PREFER_EMPTY)
                    .transform((Document document, PomTransformer.TransformationContext context) -> {
                        if (context.getContainerElement("scm").isEmpty()) {
                            final PomTransformer.ContainerElement scm = context.getOrAddContainerElement("scm");
                            scm.addOrSetChildTextElement("connection", connectionUrl);
                            scm.addOrSetChildTextElement("developerConnection", connectionUrl);
                            scm.addOrSetChildTextElement("url", url);
                        }
                    });
```


But while running against https://github.com/quarkiverse/quarkus-couchbase/, the `context.getContainerElement("scm").isEmpty()` returns true, which is wrong. 

What am I doing wrong?

**Comment by gastaldi** [comment]
Nevermind, I realized I need to pass the `project` too: 

```java
context.getContainerElement("project","scm").isEmpty()
```

**Comment by ppalaga** [comment]
Ah, there is a discrepancy between context.getContainerElement() and context.getOrAddContainerElement(). The former is based on the document, but the latter is based on `<project>`. I should document it at least.

**Pull request closed without merging**
