### PR TITLE
Downgrade to Santuario 2.3.1, add an integration test

### LINKED ISSUE #45: Add an integration test
There is just a dummy integration test ATM.

### LINKED ISSUE #46: Santuario 3.0.0 incompatible with the rest of the Quarkus ecosystem
quarkus-xmlsec currently depends on santuario 3.0.0 which depends on Jakarta XML Bind 3.0 which uses the new java packages. Not sure how useful quarkus-xmlsec can be given that the whole Quarkus ecosystem has not performed the switch to Jakarta 9/10 yet?
I wonder whether we could stay with santuario 2.3.x until Quarkus does the switch?

### PR DESCRIPTION
**Pull request by ppalaga**
Fix #46 
Fix #45

### CODE REVIEW

**Comment by ppalaga** [comment]
Could you please review @martinffx?

**Comment by ppalaga** [comment]
Any chance to review, @martinffx?

**Comment by martinffx** [comment]
@ppalaga sorry, I'll have a look at this tonight or this weekend.

**Comment by ppalaga** [comment]
Still no time to review @martinffx ? Would it perhaps be OK for you if @gastaldi grants merge permissions to me?

**Comment by martinffx** [comment]
sorry, I got sick over the weekend. No problem with you getting merge rights!

**Comment by gastaldi** [comment]
@ppalaga congratulations, you're now part of the quarkus-xmlsec team now ;)

**Comment by gastaldi** [comment]
@all-contributors add @ppalaga for code and maintenance

**Comment by ppalaga** [comment]
> I got sick over the weekend.

Get well soon!

Reviewing is still welcome now or in the future.

**Pull request merged**
