### PR TITLE
Quarkus XMLSec moved to Quarkus CXF

### LINKED ISSUE #168: Move quarkus-xmlsec to Quarkus CXF
Maintaining this project brings an additional overhead and Quarkus CXF is the primary user of quarkus-xmlsec anyway. 

Having said that, I propose to move the quarkus-xmlsec extension to Quarkus CXF and release/maintain it there.

Are there any concerns about it, @gastaldi @maxandersen?

### PR DESCRIPTION
**Pull request by ppalaga**
Fix https://github.com/quarkiverse/quarkus-xmlsec/issues/168

### CODE REVIEW

**Review by gastaldi — APPROVED** [review]
LGTM. I believe this repository can be archived too. This can be accomplished by providing a PR deleting the [terraform script](https://github.com/quarkiverse/quarkiverse-devops/blob/main/terraform-scripts/quarkus-xmlsec.tf) and the [CODEOWNERS entry](https://github.com/quarkiverse/quarkiverse-devops/blob/main/.github/CODEOWNERS#L121).

**Comment by gastaldi** [comment]
We also need to remove [the entry from the Extension Catalog](https://github.com/quarkusio/quarkus-extension-catalog/blob/main/extensions/quarkiverse-xmlsec.yaml), since it will no longer be updated

**Comment by ppalaga** [comment]
> LGTM. I believe this repository can be archived too. This can be accomplished by providing a PR deleting the [terraform script](https://github.com/quarkiverse/quarkiverse-devops/blob/main/terraform-scripts/quarkus-xmlsec.tf) and the [CODEOWNERS entry](https://github.com/quarkiverse/quarkiverse-devops/blob/main/.github/CODEOWNERS#L121).

Thanks for the hint, done here: https://github.com/quarkiverse/quarkiverse-devops/pull/220

**Comment by ppalaga** [comment]
> We also need to remove [the entry from the Extension Catalog](https://github.com/quarkusio/quarkus-extension-catalog/blob/main/extensions/quarkiverse-xmlsec.yaml), since it will no longer be updated

Done here https://github.com/quarkusio/quarkus-extension-catalog/pull/98

**Pull request merged**
